- name: Install Flask on EC2 instance
  hosts: all
  become: yes
  gather_facts: yes
  remote_user: ubuntu
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
